include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/**.freezed.dart"
    - "**.yaml"
  errors:
    invalid_annotation_target: ignore
    mixin_inherits_from_not_object: ignore
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    directives_ordering: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
